/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imbacad_model_dwg_DWG */

#ifndef _Included_imbacad_model_dwg_DWG
#define _Included_imbacad_model_dwg_DWG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imbacad_model_dwg_DWG
 * Method:    readLines
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_imbacad_model_dwg_DWG_readLines
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
