/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imbacad_model_Glm */

#ifndef _Included_imbacad_model_Glm
#define _Included_imbacad_model_Glm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imbacad_model_Glm
 * Method:    mul
 * Signature: ([F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_imbacad_model_Glm_mul
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     imbacad_model_Glm
 * Method:    translate
 * Signature: ([F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_imbacad_model_Glm_translate
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     imbacad_model_Glm
 * Method:    rotate
 * Signature: ([FF[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_imbacad_model_Glm_rotate
  (JNIEnv *, jclass, jfloatArray, jfloat, jfloatArray);

/*
 * Class:     imbacad_model_Glm
 * Method:    perspective
 * Signature: (FFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_imbacad_model_Glm_perspective
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
