/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imbacad_model_ocr_Tesseract */

#ifndef _Included_imbacad_model_ocr_Tesseract
#define _Included_imbacad_model_ocr_Tesseract
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imbacad_model_ocr_Tesseract
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imbacad_model_ocr_Tesseract_init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imbacad_model_ocr_Tesseract
 * Method:    getUTF8Text
 * Signature: ([III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imbacad_model_ocr_Tesseract_getUTF8Text
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     imbacad_model_ocr_Tesseract
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imbacad_model_ocr_Tesseract_end
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
