/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imbacad_model_ocr_Test */

#ifndef _Included_imbacad_model_ocr_Test
#define _Included_imbacad_model_ocr_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imbacad_model_ocr_Test
 * Method:    initTesseract
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imbacad_model_ocr_Test_initTesseract
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imbacad_model_ocr_Test
 * Method:    getUTF8Text
 * Signature: ([III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imbacad_model_ocr_Test_getUTF8Text
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
